name: Run Weather Script

on:
  push:
    branches:
      - main  # Replace with your main branch name
  schedule:
    - cron: '0 8 * * *'  # Schedule to run every day at 8 AM UTC, adjust as needed

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to the latest version
      with:
        python-version: '3.12'  # Set to Python 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml gspread oauth2client

    - name: Run Python script
      run: python other/scrape.py  # Replace with your path to scrape.py

    - name: Commit and push if changes
      run: |
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update weather data [skip ci]" || echo "No changes to commit"
        git push
